#!/bin/sh
# DEPRECATED -- look at sha1deep if you need this kind of functionality
#
# matchup - sorting out files which you already have somewhere else.
#
# To use, create an index, using something like the following.
#
# find backup-pictures/ -type "f" -print0 | xargs -0 sha1sum > sha1pics
#
# Then, to look up a file in the index:
#
# bash matchup sha1pics file [file...]

if [[ -z "$*" ]]; then
    echo "usage: matchup indexfile [--invert] [delimchar] file [file...]"
    echo "   --invert      show results that aren't in the index"
    echo "   delimchar     use this character as a delimiter after the filename"
    exit
fi


SHALIST=$1
shift

if [[ "x--invert" == "x$1" ]]; then
    INVERT=true
    shift
else
    INVERT=""
fi

if [[ ! -a $1 ]]; then
    DELIM=$1
    shift
else
    DELIM=" "
fi

for x in "$@"; do
    sha=`sha1sum <"$x" | cut -f 1 -d ' '` 
    if [ "x$sha" != "x" ]; then
	if grep $sha "$SHALIST" > /dev/null; then 
            if [[ -z "$INVERT" ]]; then
	        echo "$x"$DELIM`grep $sha "$SHALIST" | cut -f 3- -d ' '`
            fi
        else
            if [[ ! -z "$INVERT" ]]; then
                echo "$x did not match any files"
            fi
	fi 
    fi
done 