# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
export HISTCONTROL=ignoredups
# ... and ignore same sucessive entries.
export HISTCONTROL=ignoreboth

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
        # We have color support; assume it's compliant with Ecma-48
        # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
        # a case would tend to support setf rather than setaf.)
        color_prompt=yes
    else
        color_prompt=
    fi
fi

init_colors(){
        export GREEN="\[\033[01;32m\]"
        export YELLOW="\[\033[01;33m\]"
        export RS="\[\033[00m\]"
}

if [ "$color_prompt" = yes ]; then
   init_colors
   # GREEN\u@\hNORMAL:LIGHTBLUE\wNORMAL$
fi
unset color_prompt force_color_prompt


# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD/$HOME/~}\007"'
    ;;
*)
    ;;
esac

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

#if [ -f ~/.bash_aliases ]; then
#    . ~/.bash_aliases
#fi

# enable color support of ls and also add handy aliases
if [ "$TERM" != "dumb" ]; then
    eval "`dircolors -b`"
    alias ls='ls --color=auto'
    #alias dir='ls --color=auto --format=vertical'
    #alias vdir='ls --color=auto --format=long'
fi

# some more ls aliases
#alias ll='ls -l'
#alias la='ls -A'
#alias l='ls -CF'

export EDITOR=emacs

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
export CLASSPATH=/usr/lib/jvm/java-6-sun-1.6.0.06/lib/tools.jar
#export db_ip=ofc-n1.10gen.com
export db_ip=127.0.0.1
export db_port=2007
alias lcl="db_ip=127.0.0.1 db_port=2007 "
alias dev="db_ip=iad-sb-n6.10gen.com db_port=27017 "

alias serve="./runAnt.bash ed.appserver.AppServer --port 2008 "
alias runjs="./runAnt.bash ed.js.Shell"
alias import="./runAnt.bash ed.db.ImportBinary "

alias rundb="./db --dbpath /data/db/oom/ --port 2007 run "

alias check_licenses="./runAnt.bash ed.util.LicenseHeaderCheck "

alias sites="cd ~/gitroot/sites"
alias corejs="cd ~/gitroot/corejs"

status(){
    (
        cd
        export GIT_CONFIG=~/.gitconfig.status
        mr status | python ~/.config/scripts/strip_empty_stanzas.py
    )
}

alias erh='sudo afp_client mount -a "No User Authent" 192.168.19.17:10gen_db_backup /media/erh '
alias unerh='sudo afp_client unmount /media/erh'
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

#for x in `mr ls | grep mr | grep /home | cut -d " " -f 3`; do
# (echo $x;
# cd $x;
# git tag -l;
# )
# done

function afpcli () {
    afpcmd "afp://;AUTH=No User Authent:@$1"
}

# git branch in prompt from http://log.damog.net/2008/12/two-git-tips/
GITPS1='$(__git_ps1 ":%s")'
export PS1="${GREEN}${debian_chroot:+($debian_chroot)}\u@\h:\w${RS}${YELLOW}${GITPS1}${RS}\\$ "

if [ -f ~/.config/`hostname`.rc ]; then
   source ~/.config/`hostname`.rc
fi
