# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
# don't overwrite GNU Midnight Commander's setting of `ignorespace'.
HISTCONTROL=$HISTCONTROL${HISTCONTROL+,}ignoredups
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoreboth

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
        # We have color support; assume it's compliant with Ecma-48
        # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
        # a case would tend to support setf rather than setaf.)
        color_prompt=yes
    else
        color_prompt=
    fi
fi

init_colors(){
    # FIXME: more colors; better names; actually learn ANSI escape sequences
    # The intent is that if this function doesn't get run, all these escape
    # sequences will expand to empty strings, and do nothing.
    export GREEN="\[\033[01;32m\]"
    export YELLOW="\[\033[01;33m\]"
    export RS="\[\033[00m\]"
}

if [ "$color_prompt" = yes ]; then
   init_colors
   # GREEN\u@\hNORMAL:LIGHTBLUE\wNORMAL$
fi
unset color_prompt force_color_prompt


# git branch in prompt from http://log.damog.net/2008/12/two-git-tips/
GITPS1='$(__git_ps1 ":%s")'
export PS1="${GREEN}${debian_chroot:+($debian_chroot)}\u@\h:\w${RS}${YELLOW}${GITPS1}${RS}\\$ "

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ "$TERM" != "dumb" ]; then
    eval "`dircolors -b`"
    alias ls='ls --color=auto'
    #alias dir='ls --color=auto --format=vertical'
    #alias vdir='ls --color=auto --format=long'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
#alias ll='ls -l'
#alias la='ls -A'
#alias l='ls -CF'

export EDITOR=emacs

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/etc/bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/etc/bash_aliases ]; then
    . ~/etc/bash_aliases
fi


# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

alias erh='sudo afp_client mount -a "No User Authent" 192.168.19.17:10gen_db_backup /media/erh '
alias unerh='sudo afp_client unmount /media/erh'

function afpcli () {
    afpcmd "afp://;AUTH=No User Authent:@$1"
}
# -----

status(){
    (
        cd
        export GIT_CONFIG=~/.config/git/gitconfig.status
        mr status | python ~/.config/scripts/strip_empty_stanzas.py
    )
}

alias parse_epoch='python -c "import sys, datetime; print datetime.datetime.fromtimestamp(int(sys.argv[1]))"'
alias svn-cleanup="svn st | grep ^? | cut -c2- | xargs rm"

if [ -f ~/.config/etc.machine/`hostname -s`.rc ]; then
   source ~/.config/etc.machine/`hostname -s`.rc
fi

export EDITOR=emacs
export NETHACKOPTIONS=number_pad:1,pickup_types:$,!rest_on_space,time,color,showexp

# Not sure about the best way to do this, but in lieu of a better way to
# make git understand my email is not ethan@sundance..
export EMAIL=ethan@betacantrips.com

# I freakin' hate history expansion, because it always tries to expand
# exclamation marks in commit messages, and I never actually use it. I
# always either use Meta-. to fetch "last word" (rarely) or more often
# just use up/down/C-k/C-y to slice and dice whatever commands I need
# to.  Some people seem to think it's a great time-saver to do !$ or
# whatever, but if you have to struggle harder to think about what's
# actually going to happen, it's a false economy in my opinion. I'd
# much rather take the extra fraction-of-a-second and see what command
# I'm about to execute.

# Another great joke: ^foo^bar^ only replaces the first foo! And
# ^foo^bar^g replaces the first foo with bar, then adds a g to the end
# of whatever command you were executing. Totally useless.  This could
# actually be a useful function but I'm not willing to type
# !!:s/foo/bar/g in order to make it happen. Haven't found a better
# way, though.

set +H

# Taken from Chris Lamb <http://chris-lamb.co.uk/2010/04/22/locating-source-any-python-module/>
# Use like "cdp twisted.web"
cdp () {
  cd "$(python -c "import os.path as _, ${1}; \
    print _.dirname(_.realpath(${1}.__file__[:-1]))"
  )"
}
