;; This file is automatically generated by the multiple-cursors
;; extension.
;; It keeps track of your preferences for running commands with
;; multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        org-end-of-line
        org-self-insert-command
        paredit-backward-kill-word
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        paredit-open-round
        paredit-splice-sexp-killing-backward
        python-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        ivy-done
        ))
