#! /usr/bin/env python

HOME = '66.114.71.21'
EXPORTED_TAGS = '~/Mail/.notmuch/exported-tags'
LINKSYNC = '~/etc/mail/linksync.py'

import subprocess
import os.path
import stat

LINKSYNC_E = os.path.expanduser(LINKSYNC)
EXPORTED_TAGS_E = os.path.expanduser(EXPORTED_TAGS)
if not stat.S_IXUSR & os.stat(LINKSYNC_E).st_mode:
    print("Probably can't execute linksync.py. Please run:")
    print("  chmod u+x {}".format(LINKSYNC_E))

def call(argv):
    return subprocess.check_call(argv,
                                 stderr=subprocess.STDOUT)

call([LINKSYNC_E, '-l', 'hard', '-d', 'disk', EXPORTED_TAGS_E])
call(['ssh', HOME, "{} -l hard -d disk {}".format(LINKSYNC, EXPORTED_TAGS)])
call(["smd-pull", "sync-tags"])
call(["smd-pull", "pull-mail"])
call([LINKSYNC_E, '-l', 'hard', '-d', 'notmuch', EXPORTED_TAGS_E])
call(['ssh', HOME, "{} -l hard -d notmuch {}".format(LINKSYNC, EXPORTED_TAGS)])
